### ISSUE TITLE
Issues with Umlaute

### ISSUE THREAD

**Issue by Holger-Will** [fergiemcdowall/search-index#75] opened 2015-02-26 15:07 UTC
Words with umlaute in them such as "Gerät" do not get indexed correctly.
The word "Gerät" for example is indexed as "Ger", breaking off at "ä".
I'm pretty sure my strings are utf-8... 
Any tips how to get them to work properly?

**Comment by eklem** [comment] 2015-02-26 15:09
Guessing this is the cause of a `norch-bootstrap` issue:
https://github.com/fergiemcdowall/norch-bootstrap/issues/7

**Comment by fergiemcdowall** [comment] 2015-02-26 20:18
Pretty sure that this _should_ work if everything is indexed as utf-8. On the other hand, there are no explicit tests set up, so it might be broken. Will investigate

**Comment by fergiemcdowall** [comment] 2015-03-25 14:39
should now be fixed in master branch

**Closed by fergiemcdowall** 2015-03-25 14:39 UTC
Labels: bug

**Comment by mewwts** [comment] 2015-03-25 20:25
:+1: Yet another awesome hipster lib from @fergiemcdowall !

**Comment by fergiemcdowall** [comment] 2015-03-25 20:40
YOU KNOW IT! ;)

**Comment by eklem** [comment] 2015-04-11 21:47
Tested and works like a charm!
