### ISSUE TITLE
Possible issue with relevancy

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#365] opened 2017-03-16 10:05 UTC
For a "*"-query I get the wine "St. Bernardus Abt 12" as the last hit of 10. If I increase the pageSize, I get that same wine as the last hit. It's still valid with pageSize set to 3000, but set to 10000, it's not anymore

I know relevance calculation is a bit screwed for "*"-queries, and this may just be a not so interesting edge case, but good to document for later possible issues to appear. The id is a lot longer than the others, could be that that is what is affecting it?

Same document as last item in search result:
http://test.klemespen.com:3030/search?q={"pageSize":10,"query":{"AND":{"*":["*"]}}}
http://test.klemespen.com:3030/search?q={"pageSize":100,"query":{"AND":{"*":["*"]}}}
http://test.klemespen.com:3030/search?q={"pageSize":1000,"query":{"AND":{"*":["*"]}}}

Another document as last item in search result:
http://test.klemespen.com:3030/search?q={"pageSize":10000,"query":{"AND":{"*":["*"]}}}

**Comment by fergiemcdowall** [comment] 2017-03-16 10:52
It _should_ sort on ID descending.

**Comment by fergiemcdowall** [comment] 2017-03-16 10:55
It seems to be working as intended: the id for  "St. Bernardus Abt 12" is "54077902102" which does sort after all of the other ids

**Comment by fergiemcdowall** [comment] 2017-03-16 10:56
(unless I am missing something)

**Comment by eklem** [comment] 2017-03-17 08:08
Yes, it ends up last, but why do the same result en up last no matter what the pageSize is set to.

So, when only selecting 10 results, it ends up in 10th place, when selection 100 results, it ends up in 100th place and so on. Shouldn't it show up in the same place all the time, no matter what the pageSize is?

**Comment by fergiemcdowall** [comment] 2017-03-17 08:24
Oh- of course, yes, good question...

**Comment by eklem** [comment] 2017-03-17 08:29
But, it's for a *-search, so it's not something burning (i think) =)

**Comment by fergiemcdowall** [comment] 2017-03-17 09:00
Still nice to get the bug report though!

**Comment by fergiemcdowall** [comment] 2019-01-30 09:12
Closing for now...

**Closed by fergiemcdowall** 2019-01-30 09:12 UTC
Labels: discussion, question
