### ISSUE TITLE
Switching the data file file path dynamically to create the index

### ISSUE THREAD

**Issue by ishanuda** [fergiemcdowall/search-index#517] opened 2021-02-17 14:13 UTC
Hi,

I have configured the library in an app created with NestJS and the library is working fine in a simple setup.
My setup is as follows:

```
import si = require('search-index');

@Injectable()
export class SearchService {
  private searchIndex: any;

  constructor() {
  }

  private async initSearch(): Promise<void> {
      if (!this.searchIndex) {
          this.searchIndex = await si({
              // db: 'memdown',
              name: 'test',
          });
        }
  }
}
```

In Angular FE I have several PDF files to view using the **PDFjs** library.
These PDF files have indexed using the **Apache Solr server** and I have the indexed JSON files in the file system for each PDF file in an organized folder structure as shown below. 
These files are having lots of content and the JSON index also having lots of indexed content.

The folder structure of the PDF and index files are as follows:

```
DIR-A
  | --- DATA [contains PDF files]
  | --- INDEX [contains PDF related index in JSON]
DIR-B
  | --- DATA [contains PDF files]
  | --- INDEX [contains PDF related index in JSON]
```

Now when I init the **search-index** first time for the **DIR-A folder** content it gives me the expected result.
But when I open a document from the **DIR-B** and start to search, the **search-index** is still pointing to the **DIR-A folder**.

What I need is to switch the folder accordingly when the document switches from the FE and search the document-related index or any given dynamic path-related index.

Could someone please help me to configure the library with this flexibility?

Thank you very much.

**Comment by fergiemcdowall** [comment] 2021-02-17 15:04
Hi Ishan! Its not totally clear how to reproduce the problem from the code that you included above.

I suspect that the problem is related to the `name` init parameter? You probably need one `name` for **DIR-A** and another `name` for **DIR-B**? Or do I misunderstand?

**Comment by ishanuda** [comment] 2021-02-17 16:32
Hi @fergiemcdowall,

Thank you for the reply.

No, actually I need to have all the indexes with one name, or else I will have lots of folders created in the file system according to given different names.

First, when I try, I initialized the search-index as a local variable. and then I got this **index already used and lock issue**, so I changed the code as shown above to work.

So it is also great to have a function if available, to release the index LOC, after having the search result, so that I can use the same object for another search.

Don't know this is possible, did not see any available functions as well.

Thank you very much.

**Comment by fergiemcdowall** [comment] 2021-02-17 17:25
> First, when I try, I initialized the search-index as a local variable. and then I got this index already used and lock issue, so I changed the code as shown above to work.

I'm really sorry, but your code is not in a runnable state and neither does it reproduce the problem. The best way to report bugs or ask for help in js libs is to demonstrate the problem in a vanilla javascript file that can be run on its own without any tooling or compilation 🙂

Yes, `search-index` is `leveldb` underneath and so can only be accessed by one process at a time. This is in some ways a limitation, but also ensures speed and consistency. You always need to open/create an index, assign it to a variable, and then pass that variable around to where it is needed.

If I understand your use case correctly, you want to have one index that contains documents from several directories? And then you want to be able to filter on directories when searching?

In that case I suggest adding a `directory` field to every json document that you index:

```javascript
{
  directory: 'A',
  title: 'foo',
  body: 'bar',
  ...
}
```

...and then filtering your searches like so:

```javascript
QUERY({
  AND: [
    'directory:A',
    {
       SEARCH: [ 'search', 'terms' ]
    }
  ]
})
```

**Comment by ishanuda** [comment] 2021-02-17 18:15
Hi,

Thank you very much for the given solution and my apologies for the above statement.
I just mentioned it to describe how I got the library working at last because this is the first time I am working with the library.

As you say, yes, I need one Index, but the problem is:

1. I have a simple search that needs to do with the current document open in the FE.
2. An advanced search that needs to search all the index files (JSON files indexed by Solr) and take the result.

So in this 1st case, once the user uses the simple search I need to look into the DIR-A and read the JSON and take the result.
In the 2nd case, once the user uses the advanced search, I need to look into more DIR(s) and read the JSON files and take the result.

So as I understood **search-index** creates its own index inside the directory according to the given name when the obj is initialized right?

If that so, 
1. What is the best way to achieve the above 2 cases?
2. Once created an index using the JOSN documents, Do I need to re-create the same using the PUT method, if I need to do a search, or can I use the same existing index created by **search-index**?
3. How to add more documents to the existing index so that the existing index can be updated and re-use if the 2nd is possible?

Thank you very much

**Comment by fergiemcdowall** [comment] 2021-02-17 19:27
Im really sorry @ishanuda but this is a bit complicated, and I dont understand what you are trying to achive.

> So in this 1st case, once the user uses the simple search I need to look into the DIR-A and read the JSON and take the result.

Thats not really how any search index works. Indexes must be created ahead of time otherwise there is no point to them

> In the 2nd case, once the user uses the advanced search, I need to look into more DIR(s) and read the JSON files and take the result.

Again, search indices need to be indexed ahead of time.

Depending on your use case you could look at EXPORT and IMPORT.

**Comment by ishanuda** [comment] 2021-02-18 12:15
@fergiemcdowall,

Thank you very much for the information.

I would like to know whether there is a chat location regarding the library like gitter.im
Maybe I would be able to learn more bout the library.
Because of the lack of knowledge, I am having, I think I should learn more about the library API and how it is working, etc.

Thank you very much.

**Closed** 2021-02-20 10:48 UTC

**Comment by eklem** [comment] 2021-02-20 11:10
@ishanuda Ther is a gitter.im channel, but very little happening there, and the search-index library has been updated recently. So you won't find much useful there. Look at the tests or the demo to get a better understanding of how things work.

**Comment by ishanuda** [comment] 2021-02-21 15:09
@eklem @fergiemcdowall ,
Thank you very much for the guidance.
I will go through the example and see what I can find further.

Thank you very much
