### ISSUE TITLE
[question] matcher

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/search-index#148] opened 2015-08-13 11:43 UTC
At first: I like  your api because it is very handy and very useful.  :+1: 

I have a question: I don't understand the behaviour  of search-index:

``` javascript
options.fieldOptions = [
            {fieldName: 'title', fieldedSearch: true},
            {fieldName: 'body', fieldedSearch: true},
            {fieldName: 'spineItemPath', fieldedSearch: false},
            ...
]
```
I have set ``` {fieldName: 'spineItemPath', fieldedSearch: false}``` because I do not want to get suggestions from the matcher. It not only finds texts but also meta data like value of field  ```spineItemPath```. How can I switch it off?

Thanks!

**Comment by fergiemcdowall** [comment] 2015-08-13 16:53
So you want `spineItemPath` not to be searchable? If so, this should work:

```javascript
{fieldName: 'spineItemPath', searchable: false}
```

**Comment by larsvoigt** [comment] 2015-08-14 07:16
Hi @fergiemcdowall here is an example:
```javascript
[
  {
    "title": "Accessible EPUB 3",
    "body": "EPUB  is great.",
    "spineItemPath": "../node_modules/epub3-samples/accessible_epub_3/EPUB/index.xhtml",
     ...
  },
...
]
```
```spineItemPath``` is only metadata.
If I use the matcher functionality:
```javascript
si.match('epub', function (err, matches) {})
```
 ```matches``` contains: 
```javascript
["epub", "../node_modules/epub3-samples/accessible_epub_3/EPUB/index.xhtml"]
```
I would like to have only:
```javascript
["epub"]
```
Is it possible to prevent this behaviour?
Thanks a lot!
Lars

**Comment by fergiemcdowall** [comment] 2015-08-14 08:24
Hmmm, In this case `matches` should be `["epub"]` and NOT `["epub", "../node_modules/epub3-samples/accessible_epub_3/EPUB/index.xhtml"]`

I made a test for your case [here](https://github.com/fergiemcdowall/search-index/blob/master/test/general-tests/matching-test.js) and it seems to work as intended.

I may well be misunderstanding the problem. Maybe a good way to takle this is to rewrite the above test the way you expect it to work, and push it to the repo. (You run the test by cloning the repository, and then doing `./node_modules/.bin/mocha test/general-tests/matching-test.js`

**Comment by larsvoigt** [comment] 2015-08-14 12:58
Thank you @fergiemcdowall  for your help and the great test case scenario. 
Your test case works fine.
Unfortunately I posted the wrong ```spineItemPath```. 
Here the case which fails.

Test case data: 
``` javascript
var data = [
      {
        "title": "Accessible EPUB 3",
        "body": "EPUB  is great.",
        "spineItemPath": "epub_content/accessible_epub_3/EPUB/ch03s06.xhtml"
      },
      {
        "title": "Even More Accessible EPUB 3",
        "body": "EPUB is epubtastic",
        "spineItemPath": "epub_content/accessible_epub_3/EPUB/ch03s07.xhtml"
      },
      {
        "title": "EPUB 3 FTW",
        "body": "EPUB is fantabulous",
        "spineItemPath": "epub_content/accessible_epub_3/EPUB/ch03s08.xhtml"
      }
    ];
```
No idea why its fail. The path structure looks like the same.

**Comment by fergiemcdowall** [comment] 2015-08-14 16:56
Hei @larsvoigt - check out the [updated test](https://github.com/fergiemcdowall/search-index/blob/master/test/general-tests/matching-test.js).

Things should work if you add your docs like so:

```javascript
    si.add({
      batchName: 'epubdata',
      fieldOptions: [{
        fieldName: 'spineItemPath',
        searchable: false
      }]
    }, data, function (err) {
      //batch indexed
    });
```

(spineItemPath isnt searchable, but thats OK?)

**Comment by larsvoigt** [comment] 2015-08-17 08:46
Hi @fergiemcdowall, it is curious on my end the test fails.
``` javascript
[ 'epub',
  'epub_content/accessible_epub_3/epub/ch03s06',
  'epub_content/accessible_epub_3/epub/ch03s07',
  'epub_content/accessible_epub_3/epub/ch03s08',
  'epubtastic' ]

 1) Matching epub:  should search on all fields and get results:

      Uncaught AssertionError: expected 5 to be 2
      + expected - actual

      -5
      +2
```
What is your OS?  I'm working on a Linux-System.


Mhhh, independent form the failing test,
yes I think I use the right schema to add docs? :
https://github.com/larsvoigt/epub-full-text-search/blob/master/lib/SearchEngine.js#L113

**Comment by fergiemcdowall** [comment] 2015-08-17 08:53
The test has been altered since- am looking at it right now to try to fix it

**Comment by fergiemcdowall** [comment] 2015-08-17 13:53
Hi @larsvoigt - the test should be working again now

**Comment by larsvoigt** [comment] 2015-08-17 14:16
Phew! @fergiemcdowall I read over your preceding hints: not ```fieldedSearch``` is the right option to set but ```searchable```. Sorry! At the moment I haven't understood the different between the options. 

Now I have found the really issues:
Yes your latest test case works fine for me. But this one fails:
https://github.com/fergiemcdowall/search-index/pull/155

**Comment by fergiemcdowall** [comment] 2015-08-20 09:50
OK- closing this because the answer was to use `searchable`, and I _think_ that test works now.

**Closed by fergiemcdowall** 2015-08-20 09:50 UTC
Labels: question
