### ISSUE TITLE
Indexing json files only one level deep

### ISSUE THREAD

**Issue by kdumovic** [fergiemcdowall/search-index#204] opened 2015-10-05 23:23 UTC
More of a question than an issue...
I'm using search-index to index and query a bunch of json files. However, I've noticed that when each json file is added to the index, it is treated like a file in the batch format and only indexed one level deep. Take for instance this json file:

```(json)
{
    "CPID": "CP002",
    "id": "CP002",
    "name": "My Magnificent Element",
    "version": "0.1",
    "description": "This is a magnificent element. This is a generic description.",
    "blergh": "A search term here like myFirstSearchTerm will be found.",
    "sources": [
        {
            "name": "A search term here like mySecondSearchTerm will NOT be found.",
            "url": "Non-indexed stuff",
            "id": 9000
        },
        {
            "name": "bleh bleh",
            "url": "Lorem ipsum bleh bleh.",
            "id": 9001
        },
        {
            "name": "blah blah",
            "url": "Lorem ipsum blah blah.",
            "id": 9002
        }
    ],
    "components": [
        {
            "attr1": "myThirdSearchTerm isn't going to work out well either.",
            "attr2": "sadface"
        }
    ]
}
```

In this example, queries (in the form of `q.query = {'*': [searchTerm]};` for `myFirstSearchTerm` are successful, but queries for `mySecondSearchTerm` and `myThirdSearchTerm` are not.
With your api is there a way to enable this recursive behavior for json files? Some of these files go a few levels deep. Is there an option somewhere I'm missing?

Thank you!

**Comment by fergiemcdowall** [comment] 2015-10-06 05:00
Yes, that behavior is by design- its impossible to predict the stucture of a 'deep' object, and therefore difficult to index.

It migh be worth revisiting this though....

**Comment by mewwts** [comment] 2015-10-09 06:47
This could potentially be solved by introducing some optional mapping.

**Comment by fergiemcdowall** [comment] 2015-10-09 16:22
Would love a hint if you have any! :)

**Comment by kdumovic** [comment] 2015-10-09 17:42
Well my current strategy is to use the code suggested [here](http://stackoverflow.com/questions/19098797/fastest-way-to-flatten-un-flatten-nested-json-objects) to flatten my json files before feeding them to `SearchIndex.add()`. While this works, it seems to be leaking a huge amount of memory... I'll post a new issue about it.

**Comment by fergiemcdowall** [comment] 2015-10-09 20:17
OK- in that case I'll close this issue, since things seem to be working as intended

**Comment by fergiemcdowall** [comment] 2015-10-09 20:18
It is an interesting discussion though.

**Closed** 2016-01-25 10:25 UTC
Labels: question
