### ISSUE TITLE
Can't search on ID field

### ISSUE THREAD

**Issue by fdelavega** [fergiemcdowall/search-index#361] opened 2017-03-03 12:31 UTC
Hi,

I have updated to version 0.9.15, I am building my own levelUp instance and passing it in the options when building search-index:

```js
        level(exports.siTables[key], {
                valueEncoding: 'json',
                db: down
            }, (err, db) => {
                if (err) {
                    console.log('Index Error ' + key);
                    console.log(err);
                    p.reject();
                } else {
                    // Save built connection
                    console.log('Yes for ' + key);
                    indexDataStores[key] = db;
                    p.resolve();
                }
            })
```
```js
    var indexDb = indexDataStores[indexName];
    searchIndex({indexes:  indexDb}, function (err, si) {

    })
```

I am creating my own instance to avoid the IO error when concurrent users try to read from the index at the same time (something regarding multiple process cannot access the index)

The problem is that when I execute a search, none of the callbacks are called (data, error, or end)

```js
           si.search(q)
                .on('data', (result) => {
                    console.log('Search data');
                    console.log(result);
                    results.push(result)
                })
                .on('error', (err) => {
                    console.log('Search error');
                    console.log(err);
                    cb(err)
                })
                .on('end', () => {
                    console.log('Search finished');
                    cb(null, results)
                });
```

If I let search index create levelUp by not providing the 'indexes' option, it works properly

**Comment by fergiemcdowall** [comment] 2017-03-03 12:41
Streaming search results when providing a db is in the tests: it seems to be working for example here: https://github.com/fergiemcdowall/search-index/blob/master/test/node/mocha-tests/providing-levelup-test.js#L47-L56

Can you provide a small code snippet that reproduces the error?

**Comment by fdelavega** [comment] 2017-03-07 14:45
Hi,

I have been able to  the problem, basically, my db index was already closed when I made the search.

Now I am experiencing another issue, I migrated from 0.8 to 0.9, so I have modified the software to use the stream API, since then searching by Id is not returning any result

If I make any query different from using the id, it works

**Comment by fergiemcdowall** [comment] 2017-03-07 16:55
So searching on the id field is broken? Zoinks!

**Comment by fdelavega** [comment] 2017-03-08 11:14
Maybe is not a matter of the id field but the string format I am using,  because I have some id references in other documents, and that searches by that fields doesn't  work also.

the format is string:number, ie cat:5 or product:151

**Comment by eklem** [comment] 2017-03-08 11:47
Maybe try the [matcher](https://github.com/fergiemcdowall/search-index/blob/master/doc/autosuggest.md#use-the-matcher-functionality) @fdelavega? Then you can test matching the start of the id, and figure out the possible string-issues later?

**Comment by eklem** [comment] 2017-03-08 11:50
Search on id-field seems to work here: http://norch-vuejs.klemespen.com:3030/search?q={%22pageSize%22:10,%22query%22:{%22AND%22:{%22id%22:[%229999401%22]}}} (latest search-index through the norch server)

**Comment by fergiemcdowall** [comment] 2017-03-08 14:34
@fdelavega at this point we probably need some code that reproduces the problem. Closing for now...

**Closed** 2017-03-08 14:35 UTC
Labels: bug
