### ISSUE TITLE
Load average, LevelDB and consultancy

### ISSUE THREAD

**Issue by frankrousseau** [fergiemcdowall/search-index#261] opened 2016-03-21 11:39 UTC
Hello @fergiemcdowall,

  I'm Frank Rousseau, co-founder & CTO of Cozy Cloud a company that builds [Cozy](https://cozy.io), a FOSS platform that makes the personal server easy to manage. It allows user to easily deploy applications on their own server. These apps collaborate together by sharing the same data store.

We included `search-index` in Cozy to manage the data indexation. It helps us a lot because we provide a search feature in several applications of the platform. It works fine when we index few documents like notes and file names. But when we want to make intensive indexation (like indexing a full mailbox), it crashes. Operations done via LevelDB consumes a lot of CPU and memory until the process crashes. 

We would like to know if we could hire you for a few days in order to help us fixing this problem. Do you have any availabilities?

**Comment by ConnorKrammer** [comment] 2016-03-21 11:50
I'll just chime in as well to add an anecdote to this issue. While I was doing some indexing of my own, I discovered that Node's resource consumption was very high. In the end the process had to be done on a local machine with better specs than my server. Memory was the primary issue in my case, and would often measure in at 4-5 times the total index size. The data set in question contained about 60,000 blog comments comprising about 40 MB of text; the index size ended up being 1 GB, and memory consumption peaked at over 4 GB several times during the indexing process.

**Comment by fergiemcdowall** [comment] 2016-03-21 12:03
Hi @frankrousseau 

Yes, there are a few ways to make indexing faster and less memory intensive if you make some tradeoffs. I would be happy to help you out for a few days to help you fix this problem. If that sounds OK, you can reach me on fergus@norch.io or +47 48010355, and we can discuss possibilities.

**Comment by blahah** [comment] 2016-04-15 10:03
Piling on, I just finished indexing 1.3 million documents. The only way I could do this was:

- split the indexing into syncronous batches of 10,000 documents, with a fresh node process for each batch
- use `node --max-old-space-size=8192`

Even with this, memory usage by the node process peaked a few MB short of 8192.

The only reasons I can think of for this are:

- a memory leak
- that the entire index loaded into memory during adding

Is the latter true?

**Comment by ConnorKrammer** [comment] 2016-04-15 10:09
@blahah Ah, that's a good point that I forgot to mention in my own comment -- I couldn't get anywhere close to getting the indexing process to complete without cutting the process up into synchronous batches. I also had to use `--max-old-space-size` to override Node's default maximum.

The memory usage increased each time a batch completed, in what would form a climbing saw-tooth pattern if graphed; shortly after a batch completed it dropped precipitously. Overall, very erratic memory usage.

**Comment by fergiemcdowall** [comment] 2016-04-15 10:17
AFAIK 1.3 million docs is the world record for a single search-index instance at this point it time. If anybody has indexed more, they have certainly kept quiet about it.

Memory under indexing: Search-index doesnt load the entire index into memory- but it does load every key that will be changed into memory at the point that indexing happens. This is the tradeoff with batches- larger batches require less calibration in total, but use more memory.

That said- memory should be freed up after a batch is indexed, so this does seem to be leaky behaviour. We need to find out if the problem is in `leveldown`, `levelup`, or `search-index` itself

**Comment by blahah** [comment] 2016-04-15 10:20
:tada:  I'm going to give myself this: :trophy: 

I'm pretty sure the issue is in `search-index`, because I've put 3.5 million documents into a levelDB before, using `levelup` with `leveldown` backend. I'll double-check by putting the same 1.3 million as caused the leak above into vanilla `levelup` - will report back on the memory usage.

**Comment by fergiemcdowall** [comment] 2016-04-15 10:57
@blahah Hurrah! :balloon: :cake: :tada:

`search-index` will typically have 10-100 times as many key-value pairs as documents, depending on how long they are, and how your set your options. Also- the same key-value pair can be overwritten with every batch. If you have inserted 1.3 million into `search-index`, you may well have 20-30 million pairs into `levelup`, and possibly 100 million inserts in total (since the same keys are used in many batches).

This is a problem that it would be great to solve, and good, large datasets are surprisingly difficult to come by, so if your are OK with sharing your dataset, I would be happy to help you debug this

**Comment by blahah** [comment] 2016-04-15 11:35
Excellent! The search-index is here: https://zenodo.org/record/49813

I can also upload the raw JSON object stream if that is useful?

**Comment by fergiemcdowall** [comment] 2016-04-15 11:54
Cool! :) Yes, if you post the docs in JSON format, then I can index them and see what happens

**Comment by blahah** [comment] 2016-04-15 12:48
Raw JSON object stream is here: https://zenodo.org/record/49822 :smile:

**Comment by fergiemcdowall** [comment] 2016-04-15 12:50
:+1:

**Comment by fergiemcdowall** [comment] 2016-04-18 09:36
@blahah have just done some work on your dataset. Its quite an interesting job, because it covers a lot of the typical pitfalls that users will come up against when indexing data:

 * Dataset is quite large
 * Documents need to be reformated
 * Inconsistent IDs

It would be really useful for our small community to make a blog post about how to go about indexing this type of set using the Europe PubMed Central data. Would that be OK with you?

**Comment by fergiemcdowall** [comment] 2016-04-18 09:39
@blahah Also, re the problem about using up lots of memory when indexing. Node.js is single threaded, and a lot of the performance issues have still to be ironed out, both in the core and in the underlying libs. What I did to index your data was to break the JSON into batches, store them on file, and then iterate through them with a bash script (taking advantage of the fact that `search-index` has very fast startup/shutdown times). Each time the bash script loops, it "resets" memory usage.

**Comment by fergiemcdowall** [comment] 2016-04-18 09:41
Another advantage of this approach is that if you have any unforseen disasters on your rig, you can start up again from the last unprocessed batch

**Comment by blahah** [comment] 2016-04-18 09:57
@fergiemcdowall thanks so much for your time and attention to this. I'm very happy for you to blog about it and use this data.

I have been doing exactly what you describe RE breaking up and serialising the task. Here's my bash:

```
split -l 10000 data.json ./data_parts
for part in ./data_parts/* ; do
  node --max-old-space-size=4096 eupmc_json_to_search-index.js $part
; done
```

Can indices be merged? It would be cool to do the indexing in parallel on the parts.

For now, I'm going to bundle elasticsearch into the app (which is https://github.com/codeforscience/sciencefair btw), but I'd really like to get search-index in instead, and build tools on it for NLP. I'm funded to work on this, so please let me know if there's anything I can do to help move it along.

**Comment by blahah** [comment] 2016-04-18 09:58
@fergiemcdowall above you mention the need to reformat the documents and inconsistent IDs - can you elaborate a bit on that? (I guess you'll do this in the blog post). Is it something I can address with some data cleaning?

**Comment by fergiemcdowall** [comment] 2016-04-18 10:19
Great- will get blogging! `search-index` has really been developed with a focus on _small_ data. I have been mostly concentrating on use-cases of 50000 or less, so any help in making it scale up would be great.

`search-index` stores lots of sorted arrays, and once these arrays get too long, things start to break. The solution might be to break up arrays across several keys, use object streams instead of arrays, or even something else.

Re the document processing: `search index` needs everything to be in a document that is 1 level deep- so
```javascript
{
  "identifier":[
    {"type":"pmcid","id":"1240568"},
    {"type":"pmid","id":"11544150"},
    {"type":"pii","id":"sc271_5_1835"}
  ]

...

}
```

Needs to be flatted to for example:

```javascript
{
  "identifier~pmcid": "1240568",
  "identifier~pmid": "11544150",
  "identifier~pii": "sc271_5_1835"

...

}
```

**Closed** 2017-04-13 05:12 UTC
