### ISSUE TITLE
Duplicate values

### ISSUE THREAD

**Issue by simonecogno** [fergiemcdowall/search-index#348] opened 2017-01-10 12:51 UTC
When I search into the index I got duplicate values. I got several documents with the same id and with the same content. 

I do the query in this way:
```
storedIndex.search({query: {AND: {'*': [query.toLowerCase().trim()]}}})
.on('data', res =>console.log(res))
```

**Comment by fergiemcdowall** [comment] 2017-01-10 13:08
That shouldn't happen. Could you provide an example that replicates the problem?

**Comment by eklem** [comment] 2017-01-11 11:57
I've experienced this through `norch`, and have a testcase:

```bash
npm install norch
(... start norch)
curl https://raw.githubusercontent.com/eklem/dataset-vinmonopolet/master/dataset-vinmonopolet-sparkling.str > data.json
curl -X POST -d @data.json http://localhost:3030/add
```

Works fine when having [pageSize=10](http://oppskrift.klemespen.com:3030/search?q=%7B%22pageSize%22%3A10%2C%22category%22%3A%7B%22field%22%3A%22Land%22%7D%2C%22query%22%3A%7B%22AND%22%3A%7B%22*%22%3A%5B%22eple%22%5D%7D%7D%7D), but when increasing to [pageSize=20](http://oppskrift.klemespen.com:3030/search?q=%7B%22pageSize%22%3A20%2C%22category%22%3A%7B%22field%22%3A%22Land%22%7D%2C%22query%22%3A%7B%22AND%22%3A%7B%22*%22%3A%5B%22eple%22%5D%7D%7D%7D) you'll find duplicates. The links points to a `norch@0.8.9`-instance, but the index is a couple of days old (and using `search-index@0.9.11`)

ID: 1483953161260-1072 comes twice. You'll find duplicates longer down too.

**Comment by fergiemcdowall** [comment] 2017-01-11 15:08
Will take a look...

**Comment by fergiemcdowall** [comment] 2017-01-11 15:46
Yes, I get duplicates too. If I search like so

`curl -g http://localhost:3030/search\?q\='{"pageSize":20,"category":{"field":"Land"},"query":{"AND":{"*":["eple"]}}}'`

I get this doc twice:

```javascript
{"id":"1484148829898-1072","scoringCriteria":[{"tf":[{"gte":"*￮eple","lte":"*￮eple","tf":315,"setLength":315}],"df":{"*￮eple":1},"tfidf":{"*￮eple":94.82444863415408},"boost":0,"score":94.82444863415408}],"score":94.82444863415408,"document":{"Varenummer":9701005,"Varenavn":"Pizzolato Prosecco Brut","Volum":1.5,"Pris":299.9,"Literpris":199.9,"Varetype":["Musserende vin"],"Farge":"Lys grønngul.","Lukt":"Aroma med preg av eple og sitrus.","Smak":"Livlig, lett sitrus- og eplepreget stil.","Land":"Italia","Underdistrikt":null,"Argang":null,"Rastoff":"Glera 100%","Alkohol":11}}
```

investigating...

**Comment by fergiemcdowall** [comment] 2017-01-12 10:20
FIxed in `search-index@0.9.15` and `norch@0.8.10`. I haven't included tests, as the dataset for the test case here was a bit too large. (TODO)

**Comment by fergiemcdowall** [comment] 2017-01-12 10:20
@simonecogno thanks for opening the issue!

**Comment by bmhall3** [comment] 2018-03-08 04:14
@fergiemcdowall This issue has appeared again.   I've noticed that it happens weather I have 10 items in my dataset or 300 items in my data set.   Sometimes the dataset doubles, and I haven't figured out what could be causing it.  I made sure the items were indexed properly. Let me know if I need to open a new bug or if you need any other information.

**Comment by eklem** [comment] 2018-03-08 07:41
@bmhall3 Can you look at the IDs on your search results you get back and see if there are duplicate IDs. If it is, then it sounds like this problem or something similar. If you don't get back duplicate IDs, then it may be that you index the same content several times and you don't have defined and ID for each document/item. Then stuff is just added instead of being overwritten.

**Comment by fergiemcdowall** [comment] 2018-03-08 14:26
@bmhall3 its been a while since I looked at this- is there a way to reproduce the issue?

**Comment by bmhall3** [comment] 2018-03-08 14:31
@eklem I am getting duplicate IDs back.  Additionally, I have appendOnly as false to ensure that if I add over the ids that they will delete the old entry.   In the DB I see that it appears everything is adding properly.  

Additionally, if I return all of the results and I remove the duplicate ids then the results are correct.  Otherwise it looks the search is returning twice as many results every time.   I have also noticed that if I am paging my dataset then the issue becomes more apparent because it breaks paging.  So my theory is perhaps there is a synchronization issue that is at play especially with larger datasets.  

@fergiemcdowall If you would like I could send you a sample, but I'll need to use a different data in order to display the problem

**Comment by bmhall3** [comment] 2018-03-08 16:12
@fergiemcdowall That makes sense!  Also I did figure out the issue.  The issue is that when I'm doing the search if I don't have a promise around the function it is calling then it is calling the function multiple times.     

Thank you both for your quick response times!

**Comment by fergiemcdowall** [comment] 2018-03-08 16:35
@bmhall3 glad you got it sorted out. I wonder if `search-index` should move to a promises-based API? It seems that most people wrap it in promises these days...

**Closed by fergiemcdowall** 2018-03-08 16:35 UTC
Labels: needs more info
