### ISSUE TITLE
Error while querying & indexing at the same time. 

### ISSUE THREAD

**Issue by swissums** [fergiemcdowall/search-index#419] opened 2017-09-30 19:03 UTC
While searching and indexing pages @ the same time we get the following errors see, 5 @ https://github.com/WorldBrain/WebMemex/issues/108:

<img width="845" alt="screen shot 2017-09-29 at 06 21 26" src="https://user-images.githubusercontent.com/11180947/31048317-146d5f1e-a5c7-11e7-88e1-43ca814e803e.png">

This could be in relation to, https://github.com/fergiemcdowall/search-index/issues/371

However, since a lot has changed since that issue not sure where the problem arises from. 

Currently using lastest v search-index 0.13.0

**Comment by fergiemcdowall** [comment] 2017-10-01 06:18
Hey @swissums thanks for the bug report- if you can work out how to reproduce the error then post it here and it will almost certainly get fixed.

**Comment by poltak** [comment] 2017-10-04 03:45
Hi @fergiemcdowall. Here's a gist I was able to reproduce the errors using. Simulates searching while indexing some test data: https://gist.github.com/poltak/79d589d9833148dbff9061dd1588856a

Written some instructions and notes at the bottom. I think this one is of most interest:

> this only ever happens if [query] is set to either wildcard '*' or a term that appears in the test data

**Comment by fergiemcdowall** [comment] 2017-10-04 05:52
Great! Will take a look...

**Comment by poltak** [comment] 2017-10-05 13:01
Not sure if you've had a chance to look yet, @fergiemcdowall, so sorry if premature, but do you think it's something to do with how the scoring is done in `ScoreTopScoringDocsTFIDF`?  Would love to do anything I can to help look into things further, but not sure if that's the best place to start to get-to-know.

**Comment by fergiemcdowall** [comment] 2017-10-06 08:56
That gist fails for me too (yes, the code is a bit hairy and not to easy to dig into)

**Comment by fergiemcdowall** [comment] 2017-10-06 10:05
(the code in `search-index-searcher` that is)

**Comment by fergiemcdowall** [comment] 2019-02-15 15:35
Going to close this issue since it is related to an older version of search-index.

**Closed by fergiemcdowall** 2019-02-15 15:35 UTC
