### ISSUE TITLE
Error on search result with sample app in readme

### ISSUE THREAD

**Issue by aral** [fergiemcdowall/search-index#438] opened 2018-01-30 14:41 UTC
When a search result is found in the sample app in the readme, I get the following error:

(On macOS High Sierra 10.13.2 (17C205), Node v8.9.3, NPM v.5.6.0)

```
node index.js


search > cocoa

1 : BAHIA COCOA REVIEW
/Users/aral/ind.ie/products/indienet/spikes/search2/index.js:42
  const terms = Object.keys(data.scoringCriteria[0].df).map(function(item) {
                       ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at FetchStoredDoc.printResults (/Users/aral/ind.ie/products/indienet/spikes/search2/index.js:42:24)
    at emitOne (events.js:116:13)
    at FetchStoredDoc.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at FetchStoredDoc.Readable.push (_stream_readable.js:208:10)
    at FetchStoredDoc.Transform.push (_stream_transform.js:147:32)
    at /Users/aral/ind.ie/products/indienet/spikes/search2/node_modules/search-index-searcher/lib/FetchStoredDoc.js:19:10
    at /Users/aral/ind.ie/products/indienet/spikes/search2/node_modules/levelup/lib/levelup.js:211:7
```

Dependencies: 

```json
  "dependencies": {
    "JSONStream": "^1.3.2",
    "chalk": "^2.3.0",
    "request": "^2.83.0",
    "search-index": "^0.15.0",
    "term-cluster": "0.0.1"
  }
```

**Comment by sakono2** [comment] 2018-07-24 02:12
Possible dupe of #444

**Comment by fergiemcdowall** [comment] 2018-07-24 07:45
@aral @sakono2  thanks for the feedback- will take a look

**Comment by fergiemcdowall** [comment] 2019-01-30 11:35
Sample app is no more, however new sample app is on the way

**Closed by fergiemcdowall** 2019-01-30 11:35 UTC
